### ISSUE TITLE
App crashes when trying to load from file

### ISSUE THREAD

**Issue by Damjan94** [tema6120/ForgetMeNot#31]
I have re-installed the app(F-Droid), cleared data, and the crash still persists.
I'm running android 10 lieageOS with no google services
the app crashes as soon as I click on the "load from file" button. It doesn't even ask for storage permissions.

```
01-11 16:12:37.443 10397 10397 E AndroidRuntime: FATAL EXCEPTION: main
01-11 16:12:37.443 10397 10397 E AndroidRuntime: Process: com.odnovolov.forgetmenot, PID: 10397
01-11 16:12:37.443 10397 10397 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=text/plain }
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5210)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at v0.l.d.e.startActivityForResult(Unknown Source:10)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at v0.h.d.a.k(Unknown Source:0)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at v0.l.d.e$a.f(:1)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at androidx.fragment.app.Fragment.A0(:1)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at g.onClick(java-style lambda group:11)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.view.View.performClick(View.java:7259)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7236)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.view.View.access$3600(View.java:801)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:27892)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-11 16:12:37.443 10397 10397 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-11 16:12:37.447  3729 10457 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2

```

I tried building the app from source, but when I try to debug it, it throws yet another exception that the font is missing
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.odnovolov.forgetmenot.debug, PID: 11674
    android.content.res.Resources$NotFoundException: Font resource ID #0x7f090000 could not be retrieved.
        at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:405)
        at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:241)
        at com.odnovolov.forgetmenot.presentation.screen.home.DeckPreviewAdapter.prepareMeasuring(DeckPreviewAdapter.kt:195)
        at com.odnovolov.forgetmenot.presentation.screen.home.DeckPreviewAdapter.onCreateViewHolder(DeckPreviewAdapter.kt:50)
        at com.odnovolov.forgetmenot.presentation.screen.home.DeckPreviewAdapter.onCreateViewHolder(DeckPreviewAdapter.kt:28)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7301)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6426)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6310)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6306)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9884)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
E/AndroidRuntime:     at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 11674 SIG: 9
Disconnected from the target VM, address: 'localhost:39629', transport: 'socket'

```

**Comment by tema6120** [comment]
Thank you for reporting!

1) It seems that my app doesn't handle case when the device doesn't have the app for providing data. My app should at least show the message about this. But it would be better if I additionally wrote one's own ui for browsing files on the device. I think it's not related to asking for storage permission.

2) You are right. My app uses downloadable fonts that require google services.  I didn't take this into account.

**Comment by tema6120** [comment]
Crashes fixed.

**Comment by Damjan94** [comment]
sweet, works nice :)
