### ISSUE TITLE
Sorting doesn't work on intially seeded list?

### ISSUE THREAD

**Issue by shirshak55** [tema6120/ForgetMeNot#65]
I don't know if its weird bug but if I seed it by manually modifying app I can't sort it. If I open all of them one by one it does sort however?

In other words if I see Last Tested on all cards I can sort it otherwise sorting seems to do nothing.

**Comment by tema6120** [comment]
Yes. It works as intended. Maybe this is not entirely the right way but first of all, I wanted to display the new decks at the top of the list so that they can be easily discovered. So new decks are always at the top and are sorted by date of creation.

You can learn the sorting logic from this file: https://github.com/tema6120/ForgetMeNot/blob/master/app/src/main/kotlin/com/odnovolov/forgetmenot/presentation/screen/home/DeckPreviewComparator.kt

**Comment by shirshak55** [comment]
@tema6120 thanks. will look on it.

**Comment by shirshak55** [comment]
@tema5120 what to do if I dont want to display new decks but obey what user has selected on filter. I tried like this:

```
        return when {
            deck1.lastTestedAt == null && deck2.lastTestedAt == null ->
                deck1.createdAt.compareTo(deck2.createdAt)
            deck1.lastTestedAt == null -> deck1.deckName.compareTo(deck2.deckName)
            deck2.lastTestedAt == null ->  deck1.deckName.compareTo(deck2.deckName)
            deck1.isPinned && deck2.isPinned -> compareRegularly(deck1, deck2)
            deck1.isPinned -> -1
            deck2.isPinned -> 1
            else -> compareRegularly(deck1, deck2)
        }
```

But it only does initial sorting and doesn't obey what user has used in Sort By popup.

**Comment by tema6120** [comment]
If you want to ignore 'new decks' logic:

```kotlin
override fun compare(deck1: RawDeckPreview, deck2: RawDeckPreview): Int {
        return when {
            deck1.isPinned && deck2.isPinned -> compareRegularly(deck1, deck2)
            deck1.isPinned -> -1
            deck2.isPinned -> 1
            else -> compareRegularly(deck1, deck2)
        }
    }
```

If you also want to ignore whether the deck is pinned, do as follows:

```kotlin
override fun compare(deck1: RawDeckPreview, deck2: RawDeckPreview): Int {
        return compareRegularly(deck1, deck2)
    }
```

**Comment by shirshak55** [comment]
@tema6120 actually i tried that but it was crashing 

```
2021-08-30 10:28:48.425 20484-20484/com.shirshak.grevocabs.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shirshak.grevocabs.debug, PID: 20484
    java.lang.NullPointerException
        at com.shirshak.grevocabs.presentation.screen.home.DeckPreviewComparator.compareRegularly(DeckPreviewComparator.kt:25)
        at com.shirshak.grevocabs.presentation.screen.home.DeckPreviewComparator.compare(DeckPreviewComparator.kt:15)
        at com.shirshak.grevocabs.presentation.screen.home.DeckPreviewComparator.compare(DeckPreviewComparator.kt:7)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.util.TimSort.sort(TimSort.java:234)
        at java.util.Arrays.sort(Arrays.java:1424)
        at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:2557)
        at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:1043)
        at com.shirshak.grevocabs.presentation.screen.home.HomeViewModel$sortedDecksPreview$1.invokeSuspend(HomeViewModel.kt:124)
        at com.shirshak.grevocabs.presentation.screen.home.HomeViewModel$sortedDecksPreview$1.invoke(Unknown Source:14)
        at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$unsafeFlow$1$lambda$1.invokeSuspend(Zip.kt:33)
        at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$unsafeFlow$1$lambda$1.invoke(Unknown Source:14)
        at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:79)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
  ```

**Comment by tema6120** [comment]
You are right. I should have checked the code.
```kotlin
    private fun compareRegularly(deck1: RawDeckPreview, deck2: RawDeckPreview): Int {
        val leftDeck = if (deckSorting.direction == Asc) deck1 else deck2
        val rightDeck = if (deckSorting.direction == Asc) deck2 else deck1
        return when (deckSorting.criterion) {
            Name -> leftDeck.deckName.compareTo(rightDeck.deckName)
            CreatedAt -> leftDeck.createdAt.compareTo(rightDeck.createdAt)
            LastTestedAt -> {
                when {
                    leftDeck.lastTestedAt == null -> -1
                    rightDeck.lastTestedAt == null -> 1
                    else -> leftDeck.lastTestedAt.compareTo(rightDeck.lastTestedAt)
                }
            }
            FrequencyOfUse -> leftDeck.averageLaps.compareTo(rightDeck.averageLaps)
            Task -> {
                when {
                    leftDeck.numberOfCardsReadyForExercise == null -> -1
                    rightDeck.numberOfCardsReadyForExercise == null -> 1
                    else -> {
                        leftDeck.numberOfCardsReadyForExercise
                            .compareTo(rightDeck.numberOfCardsReadyForExercise)
                    }
                }
            }
        }
    }
```

**Comment by shirshak55** [comment]
@tema6120  Hi, I created gre vocab flashcard and modified some fonts etc. I have released it in github https://github.com/shirshak55/gre-vocabs. 

I would like to release it in playstore. If you don't have any issue let me know. Just wanted to make sure I credit you enough for this app before I publish it in playstores etc.. 

Thanks.

**Comment by tema6120** [comment]
No, I'm against it. Use my code for personal purposes.

By the way if you fork my project, you should link with my project like this https://github.com/androiddevnotesforks/ForgetMeNot

**Comment by shirshak55** [comment]
@tema6120 hmm ok I will not publish it in play store then. Do you know how we can link it I don't find it in any settings.

**Comment by tema6120** [comment]
Just click on the 'Fork' button at the top-right corner on the project site.
